import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { block } from 'million/next';



const HomeBlock = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs With Million</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js with Million!
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <p className={styles.description}>
          Check out <a href="millionjs.org">Millionjs</a>
        </p>
      </main>
    </div>
  )
}


const Home = block(HomeBlock)

export default Home;
